名称：部署到腾讯云函数

在：
  workflow_dispatch：

职位：
  建立：
    运行：ubuntu-latest
    如果：github.event.repository.owner.id == github.event.sender.id
    步骤：
      -名称：结帐
        用途：actions / checkout @ v2
        与：
          仓库：$ {{github.repository}}

      -名称：使用Node.js $ {{matrix.node-version}}
        用途：actions / setup-node @ v1
        与：
          节点版本：$ {{matrix.node-version}}

      -名称：“安装依赖和serverless工具”
        运行：|
          npm安装
          sudo npm安装无服务器-g
      -名称：“将秘密内部配置的变量添加到severless.yml里面作为环境变量”
        运行：|
          如果[$ JD_COOKIE]; 然后sed -i“ / variables / a \ JD_COOKIE：$ JD_COOKIE” serverless.yml; fi;
          如果[$ JD_USER_AGENT]; 然后sed -i“ / variables / a \ JD_USER_AGENT：$ JD_USER_AGENT” serverless.yml; fi;
          如果[$ JD_BEAN_STOP]; 然后sed -i“ / variables / a \ JD_BEAN_STOP：$ JD_BEAN_STOP” serverless.yml; fi;
          如果[$ JD_BEAN_SIGN_STOP_NOTIFY]; 然后sed -i“ / variables / a \ JD_BEAN_SIGN_STOP_NOTIFY：$ JD_BEAN_SIGN_STOP_NOTIFY” serverless.yml; fi;
          如果[$ JD_BEAN_SIGN_NOTIFY_SIMPLE]; 然后sed -i“ / variables / a \ JD_BEAN_SIGN_NOTIFY_SIMPLE：$ JD_BEAN_SIGN_NOTIFY_SIMPLE” serverless.yml; fi;
          如果[$ PUSH_KEY]; 然后sed -i“ / variables / a \ PUSH_KEY：$ PUSH_KEY” serverless.yml; fi;
          如果[$ BARK_PUSH]; 然后sed -i“ / variables / a \ BARK_PUSH：$ BARK_PUSH” serverless.yml; fi;
          如果[$ BARK_SOUND]; 然后sed -i“ / variables / a \ BARK_SOUND：$ BARK_SOUND” serverless.yml; fi;
          如果[$ TG_BOT_TOKEN]; 然后sed -i“ / variables / a \ TG_BOT_TOKEN：$ TG_BOT_TOKEN” serverless.yml; fi;
          如果[$ TG_USER_ID]; 然后sed -i“ / variables / a \ TG_USER_ID：$ TG_USER_ID” serverless.yml; fi;
          如果[$ DD_BOT_TOKEN]; 然后sed -i“ / variables / a \ DD_BOT_TOKEN：$ DD_BOT_TOKEN” serverless.yml; fi;
          如果[$ DD_BOT_SECRET]; 然后sed -i“ / variables / a \ DD_BOT_SECRET：$ DD_BOT_SECRET” serverless.yml; fi;
          如果[$ QYWX_KEY]; 然后sed -i“ / variables / a \ QYWX_KEY：$ QYWX_KEY” serverless.yml; fi;
          如果[$ IGOT_PUSH_KEY]; 然后sed -i“ / variables / a \ IGOT_PUSH_KEY：$ IGOT_PUSH_KEY” serverless.yml; fi;
          如果[$ QQ_SKEY]; 然后sed -i“ / variables / a \ QQ_SKEY：$ QQ_SKEY” serverless.yml; fi;
          如果[$ QQ_MODE]; 然后sed -i“ / variables / a \ QQ_MODE：$ QQ_MODE” serverless.yml; fi;
          如果[$ PUSH_PLUS_TOKEN]; 然后sed -i“ / variables / a \ PUSH_PLUS_TOKEN：$ PUSH_PLUS_TOKEN” serverless.yml; fi;
          如果[$ PUSH_PLUS_USER]; 然后sed -i“ / variables / a \ PUSH_PLUS_USER：$ PUSH_PLUS_USER” serverless.yml; fi;
          如果[[$ PET_NOTIFY_CONTROL]; 然后sed -i“ / variables / a \ PET_NOTIFY_CONTROL：$ PET_NOTIFY_CONTROL” serverless.yml; fi;
          如果[$ FRUIT_NOTIFY_CONTROL]; 然后sed -i“ / variables / a \ FRUIT_NOTIFY_CONTROL：$ FRUIT_NOTIFY_CONTROL” serverless.yml; fi;
          如果[$ JD_JOY_REWARD_NOTIFY]; 然后sed -i“ / variables / a \ JD_JOY_REWARD_NOTIFY：$ JD_JOY_REWARD_NOTIFY” serverless.yml; fi;
          如果[$ JD_818_SHAREID_NOTIFY]; 然后sed -i“ / variables / a \ JD_818_SHAREID_NOTIFY：$ JD_818_SHAREID_NOTIFY” serverless.yml; fi;
          如果[$ JOY_FEED_COUNT]; 然后sed -i“ / variables / a \ JOY_FEED_COUNT：$ JOY_FEED_COUNT” serverless.yml; fi;
          如果[$ JOY_HELP_FEED]; 然后sed -i“ / variables / a \ JOY_HELP_FEED：$ JOY_HELP_FEED” serverless.yml; fi;
          如果[$ JOY_RUN_FLAG]; 然后sed -i“ / variables / a \ JOY_RUN_FLAG：$ JOY_RUN_FLAG” serverless.yml; fi;
          如果[$ JOY_TEAM_LEVEL]; 然后sed -i“ / variables / a \ JOY_TEAM_LEVEL：$ JOY_TEAM_LEVEL” serverless.yml; fi;
          如果[$ JD_JOY_REWARD_NAME]；然后sed -i“ / variables / a \ JD_JOY_REWARD_NAME：$ JD_JOY_REWARD_NAME” serverless.yml; fi;
          如果[$ MARKET_COIN_TO_BEANS]; 然后sed -i“ / variables / a \ MARKET_COIN_TO_BEANS：$ MARKET_COIN_TO_BEANS” serverless.yml; fi;
          如果[$ MARKET_REWARD_NOTIFY]; 然后sed -i“ / variables / a \ MARKET_REWARD_NOTIFY：$ MARKET_REWARD_NOTIFY” serverless.yml; fi;
          如果[$ SUPERMARKET_UPGRADE]；然后sed -i“ / variables / a \ SUPERMARKET_UPGRADE：$ SUPERMARKET_UPGRADE” serverless.yml; fi;
          如果[$ BUSINESS_CIRCLE_JUMP]; 然后sed -i“ / variables / a \ BUSINESS_CIRCLE_JUMP：$ BUSINESS_CIRCLE_JUMP” serverless.yml; fi;
          如果[$ SUPERMARKET_LOTTERY]; 然后sed -i“ / variables / a \ SUPERMARKET_LOTTERY：$ SUPERMARKET_LOTTERY” serverless.yml; fi;
          如果[$ FRUIT_BEAN_CARD]; 然后sed -i“ / variables / a \ FRUIT_BEAN_CARD：$ FRUIT_BEAN_CARD” serverless.yml; fi;
          如果[$ UN_SUBSCRIBES]; 然后sed -i“ / variables / a \ UN_SUBSCRIBES：$ UN_SUBSCRIBES” serverless.yml; fi;
          如果[$ UN_BIND_CARD_NUM]; 然后sed -i“ / variables / a \ UN_BIND_CARD_NUM：$ UN_BIND_CARD_NUM” serverless.yml; fi;
          如果[$ UN_BIND_STOP_CARD]; 然后sed -i“ / variables / a \ UN_BIND_STOP_CARD：$ UN_BIND_STOP_CARD” serverless.yml; fi;
          如果[$ JDJOY_HELPSELF]; 然后sed -i“ / variables / a \ JDJOY_HELPSELF：$ JDJOY_HELPSELF” serverless.yml; fi;
          如果[$ JDJOY_APPLYJDBEAN]; 然后sed -i“ / variables / a \ JDJOY_APPLYJDBEAN：$ JDJOY_APPLYJDBEAN” serverless.yml; fi;
          如果[$ FRUITSHARECODES]；然后sed -i“ / variables / a \ FRUITSHARECODES：$ FRUITSHARECODES” serverless.yml; fi;
          如果[$ PETSHARECODES]; 然后sed -i“ / variables / a \ PETSHARECODES：$ PETSHARECODES” serverless.yml; fi;
          如果[$ PLANT_BEAN_SHARECODES]; 然后sed -i“ / variables / a \ PLANT_BEAN_SHARECODES：$ PLANT_BEAN_SHARECODES” serverless.yml; fi;
          如果[$ SUPERMARKET_SHARECODES]; 然后sed -i“ / variables / a \ SUPERMARKET_SHARECODES：$ SUPERMARKET_SHARECODES” serverless.yml; fi;
          如果[$ DDFACTORY_SHARECODES]; 然后sed -i“ / variables / a \ DDFACTORY_SHARECODES：$ DDFACTORY_SHARECODES” serverless.yml; fi;
          如果[$ DREAM_FACTORY_SHARE_CODES]; 然后sed -i“ / variables / a \ DREAM_FACTORY_SHARE_CODES：$ DREAM_FACTORY_SHARE_CODES” serverless.yml; fi;
          如果[$ JDZZ_SHARECODES]; 然后sed -i“ / variables / a \ JDZZ_SHARECODES：$ JDZZ_SHARECODES” serverless.yml; fi;
          如果[$ JDJOY_SHARECODES]; 然后sed -i“ / variables / a \ JDJOY_SHARECODES：$ JDJOY_SHARECODES” serverless.yml; fi;
          如果[$ TG_PROXY_HOST]; 然后sed -i“ / variables / a \ TG_PROXY_HOST：$ TG_PROXY_HOST” serverless.yml; fi;
          如果[$ TG_PROXY_PORT]; 然后sed -i“ / variables / a \ TG_PROXY_PORT：$ TG_PROXY_PORT” serverless.yml; fi;
          如果[$ MONEY_TREE_SELL_FRUIT]; 然后sed -i“ / variables / a \ MONEY_TREE_SELL_FRUIT：$ MONEY_TREE_SELL_FRUIT” serverless.yml; fi;
          如果[$ FACTORAY_WANTPRODUCT_NAME]；然后sed -i“ / variables / a \ FACTORAY_WANTPRODUCT_NAME：$ FACTORAY_WANTPRODUCT_NAME” serverless.yml; fi;
          如果[$ WATCH_ACCEPTBODY]; 然后sed -i“ / variables / a \ WATCH_ACCEPTBODY：$ WATCH_ACCEPTBODY” serverless.yml; fi;
          如果[$ WATCH_DOBODY]; 然后sed -i“ / variables / a \ WATCH_DOBODY：$ WATCH_DOBODY” serverless.yml; fi;
          猫serverless.yml
          环保
        env：＃因为直接读取秘密里面的值很多字符不会自动转译，导致写入serverless.yml异常，所以设置到环境变量，在读取环境变量转译过的值
          JD_COOKIE：$ {{ secrets.JD_COOKIE }}
          JD_USER_AGENT：$ {{ secrets.JD_USER_AGENT }}
          JD_BEAN_STOP：$ {{机密。JD_BEAN_STOP }}
          JD_BEAN_SIGN_STOP_NOTIFY：$ {{机密。JD_BEAN_SIGN_STOP_NOTIFY }}
          JD_BEAN_SIGN_NOTIFY_SIMPLE：$ {{机密。JD_BEAN_SIGN_NOTIFY_SIMPLE }}
          PUSH_KEY：$ {{ secrets.PUSH_KEY }}
          BARK_PUSH：$ {{ secrets.BARK_PUSH }}
          BARK_SOUND：$ {{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN：$ {{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID：$ {{ secrets.TG_USER_ID }}
          DD_BOT_TOKEN：$ {{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET：$ {{ secrets.DD_BOT_SECRET }}
          QYWX_KEY：$ {{ secrets.QYWX_KEY }}
          IGOT_PUSH_KEY：$ {{ secrets.IGOT_PUSH_KEY }}
          QQ_SKEY：$ {{ secrets.QQ_SKEY }}
          QQ_MODE：$ {{ secrets.QQ_MODE }}
          PUSH_PLUS_TOKEN：$ {{机密。PUSH_PLUS_TOKEN }}
          PUSH_PLUS_USER：$ {{ secrets.PUSH_PLUS_USER }}
          PET_NOTIFY_CONTROL：$ {{机密。PET_NOTIFY_CONTROL }}
          FRUIT_NOTIFY_CONTROL：$ {{ secrets.FRUIT_NOTIFY_CONTROL }}
          JD_JOY_REWARD_NOTIFY：$ {{机密。JD_JOY_REWARD_NOTIFY }}
          JD_818_SHAREID_NOTIFY：$ {{机密。JD_818_SHAREID_NOTIFY }}
          JOY_FEED_COUNT：$ {{个机密。JOY_FEED_COUNT }}
          JOY_HELP_FEED：$ {{ secrets.JOY_HELP_FEED }}
          JOY_RUN_FLAG：$ {{机密。JOY_RUN_FLAG }}
          JOY_TEAM_LEVEL：$ {{ secrets.JOY_TEAM_LEVEL }}
          JD_JOY_REWARD_NAME：$ {{ secrets.JD_JOY_REWARD_NAME }}
          MARKET_COIN_TO_BEANS：$ {{ secrets.MARKET_COIN_TO_BEANS }}
          MARKET_REWARD_NOTIFY：$ {{ secrets.MARKET_REWARD_NOTIFY }}
          SUPERMARKET_UPGRADE：$ {{secrets.SUPERMARKET_UPGRADE}}
          BUSINESS_CIRCLE_JUMP：$ {{secrets.BUSINESS_CIRCLE_JUMP}}
          SUPERMARKET_LOTTERY：$ {{secrets.SUPERMARKET_LOTTERY}}
          FRUIT_BEAN_CARD：$ {{ secrets.FRUIT_BEAN_CARD }}
          UN_SUBSCRIBES：$ {{ secrets.UN_SUBSCRIBES }}
          UN_BIND_CARD_NUM：$ {{机密。UN_BIND_CARD_NUM }}
          UN_BIND_STOP_CARD：$ {{机密。UN_BIND_STOP_CARD }}
          JDJOY_HELPSELF：$ {{ secrets.JDJOY_HELPSELF }}
          JDJOY_APPLYJDBEAN：$ {{ secrets.JDJOY_APPLYJDBEAN }}
          水果代码：$ {{ secrets.FRUITSHARECODES }}
          PETSHARECODES：$ {{ secrets.PETSHARECODES }}
          PLANT_BEAN_SHARECODES：$ {{ secrets.PLANT_BEAN_SHARECODES }}
          SUPERMARKET_SHARECODES：$ {{secrets.SUPERMARKET_SHARECODES}}
          DDFACTORY_SHARECODES：$ {{ secrets.DDFACTORY_SHARECODES }}
          DREAM_FACTORY_SHARE_CODES：$ {{机密。DREAM_FACTORY_SHARE_CODES }}
          JDZZ_SHARECODES：$ {{ secrets.JDZZ_SHARECODES }}
          JDJOY_SHARECODES：$ {{ secrets.JDJOY_SHARECODES }}
          TG_PROXY_HOST：$ {{ secrets.TG_PROXY_HOST }}
          TG_PROXY_PORT：$ {{ secrets.TG_PROXY_PORT }}
          MONEY_TREE_SELL_FRUIT：$ {{ secrets.MONEY_TREE_SELL_FRUIT }}
          FACTORAY_WANTPRODUCT_NAME：$ {{机密。FACTORAY_WANTPRODUCT_NAME }}
          WATCH_ACCEPTBODY：$ {{ secrets.WATCH_ACCEPTBODY }}
          WATCH_DOBODY：$ {{secrets.WATCH_DOBODY}}

      -名称：“部署到腾讯云函数”
        运行：无服务器部署
        env：
          阶段：开发
          SERVERLESS_PLATFORM_VENDOR：腾讯
          TENCENT_SECRET_ID：$ {{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY：$ {{机密。TENCENT_SECRET_KEY }}
